const ERROR_CODE_MAP = {
    CONTROLLER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "INTERNAL_SERVER_ERROR",
    INVALID_INPUT: "VALIDATION_ERROR",
    AUTH_FAILED: "AUTHENTICATION_FAILED",
    RESOURCE_NOT_FOUND: "NOT_FOUND",
  };